### ISSUE TITLE
[Suggestion] Adjust release version name

### ISSUE THREAD

**Issue by GMalvestiti** [JackFred2/MoreChatHistory#12]
When using tools like packwiz, it gives the following after you search for mod updates:

>  Warning: Modrinth versions for More Chat History inconsistent between latest version number and newest release date (mc1.19.1-1.1.1 vs 1.3.0)

I don't know if it's possible or easy to change such thing, but it's the only mod that gives this type of message.

**Comment by JackFred2** [comment]
It's an issue with the old version system I used; I use a different one for new versions but I can't really delete or change the version of the old files in case it breaks existing modpacks that already use that number.
