### ISSUE TITLE
MoreChatHistory crashing on my custom personal modpack

### ISSUE THREAD

**Issue by Cowllum** [JackFred2/MoreChatHistory#13]
I combined the Fabulously Optimized and Cobblemon Fabric Modpack w/ some other mods not included in the mentioned modpack and for some reason this mod is the one causing the crash.

https://mclo.gs/XXS6Tjt

**Comment by JackFred2** [comment]
This crash report doesn't have More Chat History installed. By the looks of it, optigui is crashing your game.

**Comment by Cowllum** [comment]
that was a quick response lol, I just changed the link because I noticed that It was the wrong one, yeah optigui is also causing issues.

I'm also reporting it now to the mod maker too

**Comment by JackFred2** [comment]
New one is because you have both longer chat history and more chat history installed; they both do the exact same thing so just pick one to keep ig

**Comment by Cowllum** [comment]
Oh wow that is such a rookie mistake LOL! Thanks for pointing that obvious mistake lmao
