### ISSUE TITLE
Question: Why 16384?

### ISSUE THREAD

**Issue by xEricL** [JackFred2/MoreChatHistory#14]
What made you choose 16384 for the max length? Is it because it's roughly the length of a max short? Why not pick a bigger or smaller number? Just asking out of curiosity.

**Comment by JackFred2** [comment]
Not for any consequential reason; it used to be configurable, but I didn't want a config library for a <4KB mod so I removed the library and picked a nice looking number. It's large enough to do the job of being able to look back through messages but not enough to cause memory issues on a very spammy server. Also yeah, it's a power of 2: 2^14
