### ISSUE TITLE
[Request] Forge version 1.20.1

### ISSUE THREAD

**Issue by mcailac** [JackFred2/MoreChatHistory#5]
Dear @JackFred2, 

If not so hard to port your mod for Forge, can you do that please? 
This is the perfect feature that is missing by default in minecraft! 
I'm forced to use forge because of other mods that are exlusively using it..
Hope it's feasible and in your plans 🙏 

Have a great day!

**Comment by JackFred2** [comment]
Sorry for the wait - looks like someone beat me to it in the meantime: https://modrinth.com/mod/morechathistory-reforged
