### ISSUE TITLE
[Enhancement] Add a command to clear the chat.

### ISSUE THREAD

**Issue by IlIlIlIIlIlIlIl** [JackFred2/MoreChatHistory#6]
Can u please add a command to clear the chat history, maybe like /morechathistory clear or just /clearchat if possible.

**Comment by JackFred2** [comment]
Vanilla has an F3 + D hotkey?

**Comment by IlIlIlIIlIlIlIl** [comment]
> Vanilla has an F3 + D hotkey?

Yeah it does nothing for me.
