### ISSUE TITLE
Failed injection check for mixins on 1.20.2

### ISSUE THREAD

**Issue by minhperry** [JackFred2/MoreChatHistory#7]
Crash report: https://mclo.gs/mNeXzPC on version MCH 1.1.1

**Comment by JackFred2** [comment]
looks to be a conflict with [meteor's better chat module](https://github.com/MeteorDevelopment/meteor-client/blob/bd48b54d1814d904fb07b4e57cf1714752dd9208/src/main/java/meteordevelopment/meteorclient/mixin/ChatHudMixin.java#L120) which has a feature doing the same thing as MCH.
