### ISSUE TITLE
Change the CurseForge slug id to match the actual one

### ISSUE THREAD

**Issue by mrbuilder1961** [JackFred2/MoreChatHistory#8]
On curseforge the slug is `more-chat-history` whereas the modrinth and actual slug is `morechathistory`. this causes issues when marking compatibility, and is just generally confusing. should be a simple fix too!

**Comment by JackFred2** [comment]
can do, though i'm pretty sure I changed it in the opposite direction at some point in history. Out of curiosity, what tool doesn't let you use project IDs / different slugs when marking dependencies? I imagine something like REI would annoy it as it uses `rei`, `roughly-enough-items` and `roughlyenoughitems`.

**Comment by mrbuilder1961** [comment]
it caused an error when i tried to publish a version of my mod chat patches that was previously incompatible with more chat history. that's no longer the case so it's not an issue for me anymore, but when the publishing plugin tried to run it couldn't find the curse forge link.

i hope that makes some sense lol!

**Comment by JackFred2** [comment]
yeah that's fair enough, was just curious. will change it when I get back to my PC after
